### PR TITLE
docs: Update CONTRIBUTING.md with release schedule

### PR DESCRIPTION
**Pull request by andymckay**
Update contributing.md

### CODE REVIEW

**Comment by shubheksha** [comment]
@andymckay, changed title and message so that Travis would stop complaining :)

**Comment by andymckay** [comment]
Thanks @shubheksha!

**Comment by kumar303** [comment]
I was trying to wait until the build is green on this one :) The way we do an auto-changelog requires some formatting and it requires a squash-and-merge so just note that for the next time. It's no biggie though, I can filter this out when I create the next changelog.

**Comment by andymckay** [comment]
Oops sorry.

**Pull request merged**
