### PR TITLE
fix: Improve debounce to catch multiple consecutive changes

### PR DESCRIPTION
**Pull request by fregante**
- Fixes https://github.com/mozilla/web-ext/issues/2249

The current behavior is effectively ignoring file changes, hence breaking the expectation that **"the extension will update on file changes"**

Changing it to update _after_ all the changes are done ensures that no file changes are lost, while only delaying the reload by half a second.

An alternative solution would be to use a "before and after" debouncer, so that the first change will be immediate, and any further changes will _also_ be handled, but after `1000ms` have gone by without events. The drawback of this is that some users might see 2 reloads instead of one, so IMHO it's a worse solution.

If this change is accepted I'll fix the tests.

### CODE REVIEW

**Comment by Rob--W** [comment]
This change should be merged with a major version bump because it changes the behavior in a way that is not backwards-compatible.

**Comment by Rob--W** [comment]
CI shows a test failure at the `npm run test-coverage` phase:

```
  1 failing

  1) watcher
       watches for changes in the sourceDir:
     AssertError: expected spy to be called once but was called 0 times
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:120:25)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:66:20)
      at Object.calledOnce (node_modules/sinon/lib/sinon/assert.js:95:17)
      at Context.<anonymous> (tests/unit/test.watcher.js:105:18)

```

**Comment by fregante** [comment]
CI is failing due to the title, but I don’t understand what's wrong with it. Can you fix it and merge the PR?

**Comment by rpl** [comment]
Merged as #2385 
Thanks @fregante 
(and my sincere apologies I couldn't get to this sooner, but I didn't forgot it was waiting for me to take care of rebase and merge it ;-)).

**Comment by fregante** [comment]
Grazie! Looking forward to the next release

**Pull request closed without merging**
