### PR TITLE
print a development version when using a custom web-ext build

### PR DESCRIPTION
**Pull request by harshitkgupta**
I have added development version number which will be branch-commithash.
added test for same.
modified .travis.yml to set NODE_ENV  to production.

### CODE REVIEW

**Comment by harshit-knit** [comment]
Why 'This branch has conflicts that must be resolved' message is shown here?
I have pushed recent package.json.

**Comment by harshit-knit** [comment]
This is my first pull request in github.
Could somebody help me in figuring out why Travis CI build failed?

**Comment by kumar303** [comment]
Hi, thanks for your patience. The error message here should be more informative, sorry about that. It's trying to tell you that the commit message did not follow our [guideline](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages). 

Because this commit is now in your branch history, feel free to close this pull request and open a new one (if that's easier). Otherwise, you'll have to use [rebase --interactive](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) to fix the commit message.

**Comment by kumar303** [comment]
moved to https://github.com/mozilla/web-ext/pull/517

**Pull request closed without merging**
