### PR TITLE
chore: Upgrade to node 10

### LINKED ISSUE #1556: web-ext requires Node >= 10
### Is this a feature request or a bug?

Bug

### What is the current behavior?

When you try to install web-ext on Node 8, you receive an error that you need Node 10. The reason for this is the `addons-linter` dependency, which depends on `dispensary`, which [requires Node 10](https://github.com/mozilla/dispensary/blob/master/package.json#L10).

It doesn't really matter for me as I can use 10 just fine, but since the release notes explicitly mention bumping the required version to 8, you might want to fix this.

### What is the expected or desired behavior?

web-ext to be able to be installed in Node 8 just fine.

### Version information (for bug reports)

````
node --version && npm --version && web-ext --version
````

This was in CI, but using web-ext 3.0.0.

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #1556.

### CODE REVIEW

**Comment by kumar303** [comment]
The node 12 failures look like they might be related to a problem in `coveralls`. You could make the node 12 tests non-blocking and file a follow-up issue to get CI working in node 12. Or maybe use an env var to skip coverage on node 12 tests (with a to-do bug) if that's easier.

**Comment by rpl** [comment]
> The node 12 failures look like they might be related to a problem in `coveralls`. You could make the node 12 tests non-blocking and file a follow-up issue to get CI working in node 12. Or maybe use an env var to skip coverage on node 12 tests (with a to-do bug) if that's easier.

@kumar303 yeah, "not using nyc on the travis windows workers" seems to the simplest workaround to this issue and I'm going to apply that workaround as part of #1738, which is also blocked on the same failure (I investigated it a bit and filed #1739 to track it and deal with it later). 

The underlying problem seems to be actually a new one of those odd npm-related issues (I've come to the conclusion that it is a hidden npm feature, "npm provides you one new free puzzle to solve per month", this month I've been particularly lucky and I got two: #1738 and https://github.com/mozilla/web-ext/pull/1726#issuecomment-546094200 :-P).

**Comment by kumar303** [comment]
> npm provides you one new free puzzle to solve per month

Ha!

**Comment by rpl** [comment]
@wagnerand we have fixed the nyc-related failure in #1742, would you mind to rebase this PR on top of the updated master branch?

**Comment by wagnerand** [comment]
@rpl All green now.

**Comment by rpl** [comment]
> @rpl All green now.

Great! thanks for rebasing the PR

**Pull request merged**
