### PR TITLE
feat: make reload desktop notifications more concise

### LINKED ISSUE #796: Make reload desktop notifications more concise
### Is this a bug or feature request?

feature

### What is the current behavior?

* change into an extension source directory
* type `web-ext run`
* edit one of the source files to create a reload error. For example: delete one of the [required fields](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/name) from your manifest.

You will see a desktop notification telling you that the extension could not be reloaded because of an error: 
web-ext-reload

### What is the expected or desired behavior?

It's hard to glance at this and know what just happened. Can we make it more concise? Here is a suggestion (but maybe there are other things we can do):

Change the body to "unknownError: error occurred while processing ...." In other words, remove "reload response error:" from the message because that's redundant. The title of the notification already tells you that an error occurred.

### Version information (for bug reports)

* **Firefox version**:
* **Your OS and version**:
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````
v6.9.4
3.10.10
1.8.1

### PR DESCRIPTION
**Pull request by StandB**
Fixes #796

Hey, this is my first pull request ever. This was the best solution I could think of but I bet there are better ways to solve this issue.

### CODE REVIEW

**Comment by StandB** [comment]
Hey, thanks for the help. I couldn't find the source of the error before. I decided to use your log message because I couldn't think of a better one,

**Comment by kumar303** [comment]
The tests are failing because you changed the way error messages are constructed. This is expected but you'll need to make all the tests pass. You can adjust the test assertion to expect the new error message. 

Here is some information about how to run the test suite (as well as our general development workflow): https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md

**Comment by StandB** [comment]
Thanks a lot for your help, I learned a ton from this. :D

**Comment by caitmuenster** [comment]
Hey @StandB, welcome to the project! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#February_2017). 

I'd love to help you set up your profile on [mozillians.org](https://mozillians.org/). Could you create an account and ping me? I'll vouch for your awesome work on this bug. 

Thanks so much for diving in and fixing this bug! I look forward to seeing you around!

**Comment by StandB** [comment]
Wow, this is awesome @caitmuenster I created an account and my link is [https://mozillians.org/nl/u/StandB/](url). Also sorry if I shouldn't have pinged you here, I couldn't really think of a better alternative.

**Comment by caitmuenster** [comment]
This was a perfect place to ping me! :) You're vouched now!

**Pull request merged**
