### PR TITLE
Added lint rule to perfer constants over variables

### LINKED ISSUE #640: Add lint rule to prefer constants over variables
### Is this a bug or feature request?

feature

### What is the current behavior?

When contributors submit pull requests, @kumar303 always tells them to use `const` instead of `let` when they are not modifying the variable.

### What is the expected or desired behavior?

We should let the robots tell them this instead! Let's add this rule and fix up the code:
````diff
diff --git a/.eslintrc b/.eslintrc
index 24680cd..66c4e3c 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -100,6 +100,7 @@
       "allowMultiplePropertiesPerLine": true
     }],
     "one-var": [2, "never"],
+    "prefer-const": 2,
     "prefer-template": 2,
     "quote-props": [1, "consistent-as-needed"],
     "quotes": [2, "single", "avoid-escape"],````

### PR DESCRIPTION
**Pull request by aniketkudale**
Fixes #640

### CODE REVIEW

**Comment by aniketkudale** [comment]
Fixes #640

**Comment by kumar303** [comment]
Hello @aniketkudale and thanks for getting this started! The next step will be to change all the variables that are not modified to `const` instead of `let` or `var`. After your change, you can see all that need changing by running `npm run lint` in your local code. In the automated tests attached to this pull request, the report is here: https://travis-ci.org/mozilla/web-ext/jobs/182206304

**Comment by rpl** [comment]
@kumar303 @aniketkudale **spoiler warning**

... and eslint can also be helpful in the fix step ;-)
but I don't want to spoiler it too much

**Comment by rpl** [comment]
@kumar303 @aniketkudale it looks like that a pull request for this issue has been also submitted by pragyes31 as #671

**Pull request closed without merging**
