### PR TITLE
fix: Limit reloads to enabled extensions in chrome extension runner

### LINKED ISSUE #2364: `web-ext run` should not enable disabled extensions
Related piece of code:

https://github.com/mozilla/web-ext/blob/dbfc0383ff509685ca8d62ad221e8e72fc1ffb38/src/extension-runners/chromium.js#L320-L323

### Is this a feature request or a bug?

Bug

### What is the current behavior?

If you have some disabled "dev" extensions, they'll be reenabled by web-ext indiscriminately when attempting to reload them,

### What is the expected or desired behavior?

Only enabled extensions should receive a "reload" command 

### Version information (for bug reports)

* **Firefox version**: cross-browser, seen in Chrome 96
* Paste the output of these commands:

````
node --version && npm --version && web-ext --version
````

v16.4.2
8.2.0
6.5.0

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #2364

### CODE REVIEW

**Comment by rpl** [comment]
@fregante this looks definitely like a reasonable short term workaround to fix #2364, thanks for filing the issue and for looking into a fix!

The CI job failure is due to the linting of the commit message. That step of the CI job will validate the commit message that github chooses by default when the PR is squashed and merged, and so:
- when the pull request has only one commit (like in this case), it checks that the single commit message follows the commit message conventions
- when the pull request has more than one commit, it checks that the pull request title follows the the commit message conventions

And so for fixing that CI job failure you just need to reword the commit message as "fix: Limit reloads to enabled extensions" (or "fix: Limit reloads to enabled extensions in chrome extension runner" to make it clear which of the extension runner the fix is about) and force push it here.

**Comment by fregante** [comment]
I can't check it out right now, but I added 2 commits that might make it pass 😅

**Comment by fregante** [comment]
Demo of this piece of code working locally:

You can see that the extension on the right is reloaded while the disabled one stays disabled:

https://user-images.githubusercontent.com/1402241/145592023-a37a658f-c6eb-48f6-8e89-c8ac7369dff9.mov

**Review by rpl — APPROVED** [review]
@fregante Thank you! (also for recording a screencast to quickly let me see the fix in use :heart: )

**Pull request merged**
