### PR TITLE
feat(cli): suggest matching commands

### LINKED ISSUE #1762: [Feture Request]: suggest matching commands
### Is this a feature request or a bug?
Feature Request

### What is the current behavior?
```bash
$ web-ext buld

Usage: web-ext [options] command

Option values can also be set by declaring an environment variable prefixed
with $WEB_EXT_. For example: $WEB_EXT_SOURCE_DIR=/path is the same as
--source-dir=/path.

To view specific help for any given command, add the command name.
Example: web-ext --help run.


Commands:
  web-ext build  Create an extension package from source
  web-ext sign   Sign the extension so it can be installed in Firefox
  web-ext run    Run the extension
  web-ext lint   Validate the extension source
  web-ext docs   Open the web-ext documentation in a browser

Options:
  --version            Show version number                             [boolean]
  --source-dir, -s     Web extension source directory.
                                                   [string] [required] [default:
                     "/home/james-the-hacker/CodeSpace/GitHub-Projects/web-ext"]
  --artifacts-dir, -a  Directory where artifacts will be saved.
                                                   [string] [required] [default:
   "/home/james-the-hacker/CodeSpace/GitHub-Projects/web-ext/web-ext-artifacts"]
  --verbose, -v        Show verbose output                             [boolean]
  --ignore-files, -i   A list of glob patterns to define which files should be
                       ignored. (Example: --ignore-files=path/to/first.js
                       path/to/second.js "**/*.log")                     [array]
  --no-input           Disable all features that require standard input[boolean]
  --config, -c         Path to a CommonJS config file to set option defaults
                                                                        [string]
  --config-discovery   Discover config files in home directory and working
                       directory. Disable with --no-config-discovery.
                                                       [boolean] [default: true]
  -h, --help           Show help                                       [boolean]
```

### What is the expected or desired behavior?
```bash
$ web-ext buld

Usage: web-ext [options] command

Option values can also be set by declaring an environment variable prefixed
with $WEB_EXT_. For example: $WEB_EXT_SOURCE_DIR=/path is the same as
--source-dir=/path.

To view specific help for any given command, add the command name.
Example: web-ext --help run.


Commands:
  web-ext build  Create an extension package from source
  web-ext sign   Sign the extension so it can be installed in Firefox
  web-ext run    Run the extension
  web-ext lint   Validate the extension source
  web-ext docs   Open the web-ext documentation in a browser

Options:
  --version            Show version number                             [boolean]
  --source-dir, -s     Web extension source directory.
                                                   [string] [required] [default:
                     "/home/james-the-hacker/CodeSpace/GitHub-Projects/web-ext"]
  --artifacts-dir, -a  Directory where artifacts will be saved.
                                                   [string] [required] [default:
   "/home/james-the-hacker/CodeSpace/GitHub-Projects/web-ext/web-ext-artifacts"]
  --verbose, -v        Show verbose output                             [boolean]
  --ignore-files, -i   A list of glob patterns to define which files should be
                       ignored. (Example: --ignore-files=path/to/first.js
                       path/to/second.js "**/*.log")                     [array]
  --no-input           Disable all features that require standard input[boolean]
  --config, -c         Path to a CommonJS config file to set option defaults
                                                                        [string]
  --config-discovery   Discover config files in home directory and working
                       directory. Disable with --no-config-discovery.
                                                       [boolean] [default: true]
  -h, --help           Show help                                       [boolean]
Did you mean build?
```

### PR DESCRIPTION
**Pull request by jamesgeorge007**
closes #1762

### CODE REVIEW

**Comment by Rob--W** [comment]
Thanks for the feature request and patch. Could you add a unit test to the following file?
https://github.com/mozilla/web-ext/blob/3c850ae49c59e6d56d7e6f189a873bb02ae30012/tests/unit/test.program.js

**Comment by jamesgeorge007** [comment]
\cc @Rob--W

**Comment by Rob--W** [comment]
As you can see from the CI build output, the new test is failing: https://travis-ci.org/mozilla/web-ext/jobs/615041182

Please update the test to make sure that it passes.

**Comment by jamesgeorge007** [comment]
@Rob--W can you give me a better picture regarding how it should be refactored as per the context?

**Comment by Rob--W** [comment]
I think that the relevant output is not an instance of UsageError. Try checking the program's output instead, like this:
https://github.com/mozilla/web-ext/blob/f9929dad76cf357eda60871947a06b35d254b458/tests/unit/test.program.js#L103-L105

**Comment by Rob--W** [comment]
Could you revert the change to package-lock.json? The audit failure has been fixed on master, and if you rebase your patch on master, then that failure should go away.

The build still fails with the latest version of your patch. I took a closer look, and see why. Your unit test uses the `Program` constructor to run the program. But the `recommendCommands()` configuration is only defined in the `main` function. To test the desired behavior, you need to run the program instead of calling the constructor.

Here are examples:
- https://github.com/mozilla/web-ext/blob/7c0f282db5ea6bd44aaa97b19701b64f84893655/tests/functional/test.cli.nocommand.js
- https://github.com/mozilla/web-ext/blob/961da0c27cea875484338fcb0801d10229672df1/tests/functional/test.cli.run.js

Add a new test, e.g. with the file name `tests/functional/test.typo.run.js`

**Comment by Rob--W** [comment]
Have you run the tests locally? The test is failing because the `assert` object has not been imported.

And the linting fails because the test imports symbols that it does not use.

Remove unused imports and import `assert to resolve these errors.

**Comment by jamesgeorge007** [comment]
\cc @Rob--W

**Comment by Rob--W** [comment]
Thanks for the feature request and patch!

**Pull request merged**
