### PR TITLE
fix: Changed npm dependency from require-uncached to import-fresh 

### PR DESCRIPTION
**Pull request by sibiraj-s**
`require-uncached` is renamed to `import-fresh`.

### CODE REVIEW

**Comment by rpl** [comment]
I've just approved and merged this PR. Thanks @sibiraj-s!

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @sibiraj-s! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you.

**Comment by sibiraj-s** [comment]
@caitmuenster Sure. thanks. here is my profile https://mozillians.org/en-US/u/sibiraj-s/

**Comment by caitmuenster** [comment]
Awesome! Your profile is vouched. ✨

Welcome onboard! I look forward to seeing you around.

**Pull request merged**
