### PR TITLE
refactor: Make the help text more accurate for --warnings-as-errors

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by kumar303** [comment]
@josteink do you think this is a better help text? I wanted to make it clear that warnings will still be warnings in the output.

**Comment by josteink** [comment]
I think the existing text is fine, but I can see how it may be considered insufficient/confusing.

Adding your suggestion to the existing text would IMO be a better option than removing the existing text all together.

**Comment by josteink** [comment]
Yeah that looks good to me. No objections.

**Comment by kumar303** [comment]
ok, I added the original text. It's not really accurate to say that warnings are errors though because they will be only called "warnings" in the report.

**Comment by kumar303** [comment]
Thanks for the review

**Pull request merged**
